// Code generated by MockGen. DO NOT EDIT.
// Source: taskservice/interface.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
)

// MockITaskDBService is a mock of ITaskDBService interface
type MockITaskDBService struct {
	ctrl     *gomock.Controller
	recorder *MockITaskDBServiceMockRecorder
}

// MockITaskDBServiceMockRecorder is the mock recorder for MockITaskDBService
type MockITaskDBServiceMockRecorder struct {
	mock *MockITaskDBService
}

// NewMockITaskDBService creates a new mock instance
func NewMockITaskDBService(ctrl *gomock.Controller) *MockITaskDBService {
	mock := &MockITaskDBService{ctrl: ctrl}
	mock.recorder = &MockITaskDBServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockITaskDBService) EXPECT() *MockITaskDBServiceMockRecorder {
	return m.recorder
}
