###############################################################################
#       Local Settings configuration, please keep gitignored.                 #
#                Must be named localConfig.yaml (or .yml)                     #
# REQUIRED : Must change values if using local settings file for configuraion #
###############################################################################

dbUsername: "root"
dbPassword: "password123"
dbName: "dootoday"

dbHostName: "127.0.0.1"
dbPort: 3306
dbDriver: "mysql" # Mysql recommended


#############################
# Optional, but recommended #
#############################

debug: true                        # Highly recommended

##################################
# Optional: Not likely to change #
##################################

serverHostName: "http://localhost" # Hostname to run this api on
serverPort:  "9060"               # Port to run this api on

##################################
# JWT TOKEN SECRETS              #
##################################

accessTokenSecret: "access-this-is-a-very-secret-string"
refreshTokenSecret: "refresh-this-is-a-very-secret-string"

##################################
# RAZORPAY API KEY               #
##################################

razorpayKey: "rzp_test_oW4N8eXjSQAzY8"
razorpaySecret: "ds1XkOEFtZQ8BsdAkPN4Nh5n"

##################################
# URLS                           #
##################################

frontEndBase: "http://localhost:3000"
backeEndBase: "http://localhost:9060"

##################################
# ASSETS                         #
##################################
dooTodayLogo: "https://dootoday-assets.s3.ap-south-1.amazonaws.com/logo-200x200.png"
dooTodayName: "DooToday"
dooTodayDesc: "Daily task simplified"